// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191101060457_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("WebApplication1.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataNasc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataNasc = "12/10/2019",
                            Nome = "Maria",
                            ProfessorId = 1,
                            Sobrenome = "Das Dores"
                        },
                        new
                        {
                            Id = 2,
                            DataNasc = "10/04/2010",
                            Nome = "João",
                            ProfessorId = 1,
                            Sobrenome = "Pedro"
                        },
                        new
                        {
                            Id = 3,
                            DataNasc = "10/10/2010",
                            Nome = "Gabriel",
                            ProfessorId = 1,
                            Sobrenome = "Rodrigues"
                        },
                        new
                        {
                            Id = 4,
                            DataNasc = "05/07/1998",
                            Nome = "Rodrigues",
                            ProfessorId = 1,
                            Sobrenome = "Carneiro"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Prof Paula"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Prof Fernando"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Aluno", b =>
                {
                    b.HasOne("WebApplication1.Models.Professor", "Professor")
                        .WithMany("Alunos")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
